name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/*'
      - 'Dockerfile*'

jobs:
  build:
    runs-on: default-linux

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Get Runner proxy settings
      id: getproxy
      run: |
        echo "http_proxy=${HTTP_PROXY}" >> $GITHUB_OUTPUT
        echo "https_proxy=${HTTPS_PROXY}" >> $GITHUB_OUTPUT
        echo "no_proxy=${NO_PROXY}" >> $GITHUB_OUTPUT

    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          env.http_proxy=${{ steps.getproxy.outputs.http_proxy }}
          env.https_proxy=${{ steps.getproxy.outputs.https_proxy }}
          "env.no_proxy='${{ steps.getproxy.outputs.no_proxy}}'"

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image (Debian)
      uses: docker/build-push-action@v6
      with:
        build_args: |
          "http_proxy=${{ steps.getproxy.outputs.http_proxy }}"
          "https_proxy=${{ steps.getproxy.outputs.https_proxy }}"
        context: .
        file: Dockerfile.debian
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        tags: ghcr.io/haveacry/twc3teslamate:debian

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        build_args: |
          "http_proxy=${{ steps.getproxy.outputs.http_proxy }}"
          "https_proxy=${{ steps.getproxy.outputs.https_proxy }}"
        context: .
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        tags: ghcr.io/haveacry/twc3teslamate:latest,ghcr.io/haveacry/twc3teslamate:alpine
