name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/speedst3r/twc3teslamate:latest,ghcr.io/speedst3r/twc3teslamate:alpine

    - name: Build and push Docker image (alpine)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.debian
        tags: ghcr.io/speedst3r/twc3teslamate:debian
